version: '3'

services:

  carnival.db:
    container_name: carnival.db
    hostname: db
    build:
      dockerfile: ./db/db.dockerfile
      context: ./
    ports:
      - '5535:5432'
    environment:
      POSTGRES_DB: carnival
      POSTGRES_USER: carnival
      POSTGRES_PASSWORD: carnival
      PGDATA: /data/postgres
    volumes:
      - ./pgdata:/data/postgres

  carnival.web:
    container_name: carnival.web
    image: nginx:stable-alpine
    hostname: web
    volumes:
      - '../web:/var/www/carnival'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/logs:/var/log/nginx'
    ports:
      - '8888:80'

  carnival.php:
    container_name: carnival.php
    build:
      dockerfile: ./php/php.dockerfile
      context: ./
    volumes:
      - '../web:/var/www/carnival'
      - './php/z-errors.ini:/usr/local/etc/php/conf.d/z-errors.ini'
      - './php/z-upload.ini:/usr/local/etc/php/conf.d/z-upload.ini'
